 CREATE TABLE CONTACTS (
  UUID uuid PRIMARY KEY,
  FIRST_NAME CHARACTER (50) NOT NULL,
  LAST_NAME CHARACTER(50) NOT NULL,
  HOME_PHONE CHARACTER(30),
  WORK_PHONE CHARACTER(30),
  MOBILE_PHONE CHARACTER(30)
  );